name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

pool:
  vmImage: ubuntu-latest

trigger:
- develop
- main

stages:
  #DotNet Intregration Test
- template: dotnet/stages.yml
  parameters:
    shouldPublish: false
    build: DotNet_Development
    projectSrc: tests/integration/src/dotnet/library
    environments:
      - env: env
        name: DotNet_Development
  #DotNet Web Intregration Test
- template: dotnetweb/stages.yml
  parameters:
    system: test
    suffix: do
    devopsOrg: wcom-public
    build: DotNetWeb_Development
    projectSrc: tests/integration/src/dotnet/web
    shouldDeploy: false
    environments:
      - env: env
        name: DotNetWeb_Development
  #SQL Intregration Test
- template: sql/stages.yml
  parameters:
    system: test
    suffix: do
    devopsOrg: wcom-public
    projectSrc: integrationtests/src/sql
    serverName: 'devops'
    build: SQL_Development
    shouldDeploy: false
    shouldPublish: false
    databases:
      - name: DevOps
    environments:
      - env: env
        name: SQL_Development
        deploy: false