jobs:
  - deployment: ${{ format('{0}_Publish', parameters.name) }}
    displayName: ${{ parameters.name}} Publish
    environment: ${{ parameters.name}}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
              displayName: Checkout $(Build.DefinitionName)

            - task: UseDotNet@2
              displayName: 'Use .NET SDK (global.json)'
              inputs:
                packageType: sdk
                useGlobalJson: true

            - template: ../dotnetcommon/dotnet_auth.yml
              parameters:
                sources: ${{ parameters.sources }}
                onlyPublish: true

            - download: current
              displayName: Download $(Build.DefinitionName) Artifact
              artifact: $(Build.DefinitionName)

            - ${{ if parameters.sources }}:
              - ${{ each source in parameters.sources }}:
                - ${{ if eq(source.publish, true) }}:
                  - script: dotnet nuget push --api-key "${{ coalesce(source.token, '', '$(System.AccessToken)') }}" --source "${{ source.name }}" "$(Pipeline.Workspace)/$(Build.DefinitionName)/*.$(Build.BuildNumber).nupkg"
                    displayName: 'Publish to ${{ source.name }} Feed'