jobs:
  - job: Build
    displayName: ${{ format('{0} Build SSDT', parameters.name) }}
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK (global.json)'
      inputs:
        packageType: sdk
        useGlobalJson: true

    - template: ../dotnetcommon/dotnet_auth.yml
      parameters:
        sources: ${{ parameters.sources }}

    - template: ../dotnetcommon/prebuild_common.yml
      parameters:
        preBuildScript: ${{ parameters.preBuildScript }}

    - script: dotnet pack ${{ parameters.projectSrc }} -p:OutputPath=$(Build.ArtifactStagingDirectory)/$(Build.DefinitionName)/artifacts/Dacpac --output $(Build.ArtifactStagingDirectory)/$(Build.DefinitionName)/artifacts/NuGet -p:Version=$(Build.BuildNumber) ${{ parameters.buildParameters }}
      displayName: 'DotNet Pack'

    - publish: "$(Build.ArtifactStagingDirectory)/$(Build.DefinitionName)/artifacts/Dacpac"
      displayName: 'Publish $(Build.DefinitionName) Dacpac Artifact'
      artifact: $(Build.DefinitionName).Dacpac

    - publish: "$(Build.ArtifactStagingDirectory)/$(Build.DefinitionName)/artifacts/NuGet"
      displayName: 'Publish $(Build.DefinitionName) NuGet Artifact'
      artifact: $(Build.DefinitionName).NuGet