jobs:
  - deployment: ${{ format('{0}_Deploy', parameters.name) }}
    displayName: ${{ parameters.name}} Deploy
    environment: ${{ parameters.name}}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: $(Build.Repository.Name)
              displayName: Download $(Build.Repository.Name) artifact

            - script: dotnet tool install -g microsoft.sqlpackage
              displayName: Install SqlPackage

            - task: AzureCLI@2
              displayName: Deploy $(Build.Repository.Name) Artifact to "${{ parameters.name }} environment."
              inputs:
                azureSubscription: '${{ parameters.azureSubscription }}'
                scriptType: pscore
                scriptLocation: inlineScript
                inlineScript:  |
                  SqlPackage /Action:Publish /SourceFile:"$(Pipeline.Workspace)/$(Build.Repository.Name)/**.dacpac" /TargetConnectionString:"${{ parameters.connectionString }}"