jobs:
  - job: Publish
    displayName: ${{ format('{0} Publish', parameters.name) }}
    steps:
    - script: dotnet build --output "$(build.artifactstagingdirectory)" ${{ join(' ', parameters.buildParameters) }}
      displayName: 'DotNet Build'

    - publish: "$(build.artifactstagingdirectory)"
      displayName: 'Publish $(Build.Repository.Name) Artifact'
      artifact: $(Build.Repository.Name)